### ISSUE TITLE
Sometimes words with double consonants fail

### ISSUE THREAD

**Issue by furious-luke** [didoesdigital/typey-type#113]
Hi there! Firstly, thanks for creating such an incredibly useful tool for learning stenography. It's really wonderful!

I've encountered a bit of an odd issue, and have been unable to find others talking about it, so I suspect it may be something I'm doing wrong. I've noticed that quite often when I'm writing a word with double consonants, the word fails to be recognised a number of times, before eventually working. I'll give some examples...

![image](https://user-images.githubusercontent.com/561722/211428000-31198317-cc7e-49f5-a858-0df3badd8781.png)

When writing "whipped", I've found that the result will very often be "whiped", as shown in the above image. Typically I need to repeat the word 2 to 3 times before it is recognised as "whipped".

![image](https://user-images.githubusercontent.com/561722/211428335-5e9fbbf9-a5e6-419f-b7a3-20997d25bf0c.png)

Here's another example trying to type "rugged". I have many other examples I can provide if you'd like.

I have been **extremely** careful in my typing whenever I come across a double consonant word, just to make sure it's not an accuracy issue on my part. It happens so frequently that I don't believe it can be simply attributed to mistakes on my part, at least not mistakes like a key mis-stroke; it could still be a mis-configuration or something along those lines, I suppose.

I've also tried typing these words in a different application (word doc, for example), and the same kind of issue does not seem to occur at all. This indicates to me that it's not an issue with the keyboard I'm using (a Plover).

Any insights you may be able to offer would be greatly appreciated, and thanks again for the wonderful app!

**Comment by furious-luke** [comment]
Hi again! I encountered the same issue this morning quite a lot with the word "press". I wanted to try to make sure it wasn't in fact an issue with the keyboard or drivers, and so I opened up the "paper tape" system that comes with Plover to track the key strokes registered by the drivers.

This first image is the Typey Type screenshot of the word "press" failing ...

![image](https://user-images.githubusercontent.com/561722/211671193-d7dec6e5-2ca1-4fd4-8ef0-9bcfb71d4d6b.png)

And this is the associated paper tape ...

![image](https://user-images.githubusercontent.com/561722/211671248-5e7a4ced-54e9-4ec7-83e3-99cd0651eb19.png)

I managed to get only one chord for "press" to work before it failed. The paper tape seems to indicate the exact same chord was used for both, yet the second one failed in Typey Type.

**Comment by furious-luke** [comment]
After checking out the code, adding some logs, and confirming the input received by Typey Type from the Plover keyboard, I think the error is most likely something in the orthography rules within the Plover drivers. [I've found an issue here](https://github.com/openstenoproject/plover/issues/45) that might be related to what I'm seeing. I'll close this issue for now, as it's looking very much like Typey Type is just going on what it's receiving.

**Comment by didoesdigital** [comment]
How intriguing! Some thoughts that spring to mind for debugging:

- `WHEUPD` should produce "whipped" regardless of [orthography rules](https://sites.google.com/site/learnplover/lesson-7-orthography-rules-and-suffix-keys) if there's an active dictionary entry that matches precisely like `"WHEUPD": "whipped",`. I believe that entry is in both Typey Type's dictionaries and the latest version of Plover's dictionary.  Another dictionary (possibly an old Plover dictionary) without that entry would instead rely on orthography rules.
- An older version of Plover might behave differently. Looking over [the history of the main orthography rules file](https://github.com/openstenoproject/plover/commits/master/plover/system/english_stenotype.py), it looks to me like the specific examples of rugged and whipped would fall into the the "defer + ed" rule that's been there from the start, and I can't see other obvious changes that might affect those.
- Typically when I see orthography rule issues, it's where some other stroke has intervened, like if I wrote `WHEUP/-Z/PW*PB/-D`, the backspace entry would interrupt the orthography behaviour. Given the paper tape you shared, that doesn't seem like the issue here.
- If I'm typing on an unstable steno board, like my old Georgi, sometimes a key I press doesn't send a signal to the laptop. It might be worth trying to replicate the issue on another piece of hardware, like a regular qwerty keyboard with a short dictionary entry (e.g. `PRES`), or another steno machine if you have one.
- For something like "pres" missing the final "s", I sometimes see similar behaviour where Plover gets into a bad state, things start to slow down, some letters disappear, then it notifies me with an error like "Keystrokes may have been missed." I'm still not quite sure why/when that happens. My hunch would be memory issues. This seems like the most likely explanation to me, but you should have seen a notification if that were the case.
- Last idea, if you have a suitable device, you might try running Plover on a different protocol, like "Keyboard", "Gemini", or "TX bolt"

I hope you get to the bottom of it!

**Comment by furious-luke** [comment]
@didoesdigital Thanks for the detailed response, it's very much appreciated!

> Another dictionary (possibly an old Plover dictionary) without that entry would instead rely on orthography rules.

I'm running on a completely stock, unmodified, version of the Plover software. I'm pretty new to stenography, and so have  not modified any of the configuration.

> An older version of Plover might behave differently.

I'm running on `4.0.0.dev12`, which is the latest version according to the Plover GitHub project page.

> If I'm typing on an unstable steno board, like my old Georgi, sometimes a key I press doesn't send a signal to the laptop. It might be worth trying to replicate the issue on another piece of hardware, like a regular qwerty keyboard with a short dictionary entry (e.g. PRES), or another steno machine if you have one.

Interestingly, during my investigations I found out about the Plover keystroke log file. I've enabled and examined it and the results are especially confusing. The log file suggests that Plover actually knows about the correct translation; it registers the keys "PRES" and then also says that the translation is "press", however TypeyType still only receives the word "pres" from the Plover software.

> Last idea, if you have a suitable device, you might try running Plover on a different protocol, like "Keyboard", "Gemini", or "TX bolt"

I currently have it running on "Gemini PR", but I will see if I can explore those other protocols.

Thanks again for your help!
