### ISSUE TITLE
Speak words with sound option ignores various tts engine options (Linux)

### ISSUE THREAD

**Issue by Beethoven-n** [didoesdigital/typey-type#140]
the Speak words with sound option seems to override both my speechd.conf and my about:config setting in Firefox clearly setting the voice to a different one. i can verify that the config option is properly set because the voice that `spd-say` uses by default is indeed different from the one that i have set in my configs.
the voice chosen by the program pronounces words such as "has" like "as," and is genuinely hard to listen to, so it'd be much appreciated to use something else

here's a quick spec sheet to give context
distro: arch linux
kernel version: 6.5.9-arch2-1
speech-dispatcher version: 0.11.5
espeak-ng version: 1.51.1
mbrola version: 1:3.3-1

**Comment by didoesdigital** [comment]
Thanks for flagging this @Beethoven-n. I know very little about arch linux, but I do know that web speech is weird and complicated. I would have a hard time debugging the issue to resolve it specifically for those device specs but I think adding options to choose the language and voice should help so I created an issue for that: https://github.com/didoesdigital/typey-type/issues/141

Typey Type currently overrides/sets almost nothing apart from the [HTML `lang="en"` here](https://github.com/didoesdigital/typey-type/blob/b45aee4e186efd97809834179e4fd08c0f763936/public/index.html#L2). The [bulk of the speech synthesis code is here](https://github.com/didoesdigital/typey-type/blob/b45aee4e186efd97809834179e4fd08c0f763936/src/App.js#L2091-L2144). If you can work out what specific patch might help your situation, we can look into it. Otherwise, my best guess is to add the options I mentioned in https://github.com/didoesdigital/typey-type/issues/141 and hope that sorts it out.

**Comment by Beethoven-n** [comment]
woah! surprised by the fullness of the answer. how would i apply these settings on firefox?

**Comment by Beethoven-n** [comment]
could be that the code responsible for voices is [commented out](https://github.com/didoesdigital/typey-type/blob/b45aee4e186efd97809834179e4fd08c0f763936/src/App.js#L2115C12-L2115C12)

**Comment by Beethoven-n** [comment]
aha, perhaps that's not it! it appears to be either an espeak-ng bug or a speech-dispatcher bug, because its espeak-ng module gives me this error when i get it to speak with just the module: `sd_espeak-ng: espeak.c:596: espeak_set_voice: Assertion `msg_settings.voice.language' failed.`

**Comment by didoesdigital** [comment]
@Beethoven-n that sounds to me like something around how espeak-ng is installed/configured that you'll need to debug on your device.

Meanwhile, I've added a "Voice" setting to the UI fixing https://github.com/didoesdigital/typey-type/issues/141, which will hopefully give you and other people using the "Speak words with sound" setting more control over the voice instead of only poor default voices. To try it out, you can hard refresh Typey Type to see the latest version.

Please let me know if you think we can close this issue now.

**Comment by didoesdigital** [comment]
It seems like this issue is likely addressed as much as Typey Type itself can support so I will close this for now. @Beethoven-n please comment if you think it needs to be re-opened.
