### ISSUE TITLE
Separate import/export features on Progress page

### ISSUE THREAD

**Issue by na2hiro** [didoesdigital/typey-type#160]
Hi, thanks for the great site!

Import/export feature takes the big part of top of [Progress page](https://didoesdigital.com/typey-type/progress), but I think "My Progress" is the main and I think it should come at the top. When I first visited this page, I was intimidated by the big text and thought what all this page offers is to save and load stuff, and navigated away and thought lessons page is the place to do actual practice (I later found My Progress and the recommendation are very useful and they're my go-to now!)

(How it looks today)
<img width="1039" alt="my-progress-current" src="https://github.com/didoesdigital/typey-type/assets/736244/a8251eb7-66a5-4881-9057-ef048aaa5c3f">

What do you think about showing My Progress at the top of the page and putting the import/export features somewhere else? I played around with the code and tested to put in a separate modal which can be triggered by a button placed where "download" link exists today.

<img width="1223" alt="my-progress-import-export" src="https://github.com/didoesdigital/typey-type/assets/736244/804a4d74-7d47-4ffd-ad7c-8c9803707c96"> 
<img width="1227" alt="my-progress-import-export-modal-opened" src="https://github.com/didoesdigital/typey-type/assets/736244/9a7a2962-84da-47eb-b5fc-182057ae8d88">

The code change I made is https://github.com/didoesdigital/typey-type/commit/d0ddbe2ce987a0a8f24fad307b3e34d504916b29. I can brush it up if this sounds good

**Comment by didoesdigital** [comment]
@na2hiro thanks for sharing this! I really appreciate you including the specific detail about how you thought that "all this page offers is to save and load stuff". That sounds important to address.

However, the reason the warning is so big and obnoxious is that in the past people using Typey Type have *often* lost their progress because they did not save it. So it's really important that this message is extremely prominent.

Once the student has typed more than 2000 words, that page shows a reduced version of the import/export form that is less daunting:

<img width="1421" alt="Screenshot of Typey Type progress page. Your progress: You’ve successfully typed 9579 words without misstrokes. You’re 96% of the way to 10,000 words. Links to Practice your words, Drill 789 memorised words, Revise 8790 seen words, Discover new words. Load and copy buttons." src="https://github.com/didoesdigital/typey-type/assets/2476974/dc4536b7-26ca-449e-b6fa-9e919a1445b7">

@na2hiro can you think of some other approaches to balance the challenge you described of being aware of what's on the page as well as ensuring people are aware of why/how/where to save their progress?

**Comment by didoesdigital** [comment]
Oh, I forgot to include `You can also clear your progress by loading in empty curly braces, {}.` somewhere in the mock up, but that should be there too.

**Comment by na2hiro** [comment]
That mockups look awesome! I wonder if you have saved the mockup code so I can base off of (especially style)

**Comment by didoesdigital** [comment]
I prototyped the mockups in the browser. Here's the resulting markup…

Notification:

```
<div class="notification notification--global  w-100 flex wrap justify-between pa1 p1 p3 pa3 mb3 items-center bg-danger dark:text-coolgrey-900">
  <div class="notification__message">
    <p class="mb0">
      <strong>Back up your progress regularly:</strong> Your progress data is saved in your browser. You’ll lose your progress if you clear your browsing data (history, cookies, and cache). <button class="de-emphasized-button">Learn more</button>.
   </p>
  </div>
  <button class="de-emphasized-button flex items-center justify-center p1" aria-label="Dismiss notification">
    <span class="icon" style="display: inline-block; mask: url(&quot;/typey-type/static/media/ClosingCross.e18cfc9be01581b8127611e43f8ea303.svg&quot;) center center / contain no-repeat; width: 1em; height: 1em;"></span>
  </button>
</div>
```

Modal:

```
<h3 id="aria-modal-heading">Back up your progress</h3>
<p>Typey Type saves your typing progress in your browser’s local storage. <span class="bg-danger">You’ll lose your progress if you clear your browsing data (history, cookies, and cache).</span> If you share this device with other people or use Typey Type across several devices and browsers, you should save your progress elsewhere.</p>
<h3>Save progress</h3>
<p>You can:</p>
<ul>
  <li>Copy your progress to your clipboard and save it in a text file somewhere safe, or</li>
  <li>Hit “Download progress file” to save your progress as a JSON file.</li>
</ul>
<h3>Load progress</h3>
<p>When you return, hit “Load progress” and enter your progress to load it back into Typey Type. You can also clear your progress by loading in empty curly braces, <code>{}</code></p>
```
