### ISSUE TITLE
Exact spacing accepts no spaces?

### ISSUE THREAD

**Issue by na2hiro** [didoesdigital/typey-type#166]
I was writing end-to-end test cases for each spacing option and found out that "Exact spacing" doesn't allow any spacing between words, so it require for example "washersaid" instead of "was her said". You can easily check this with QWERTY keyboard on any lesson

If it's intended, then please close this. I expected it to require exactly 1 space between words

<img width="386" alt="Screenshot 2024-04-24 at 17 18 17" src="https://github.com/didoesdigital/typey-type/assets/736244/d57feb13-b3eb-4a95-9832-2f15be3a57d3">

An idea for the implementation is to match like "space before" strategy, except for the first word that keeps the current behavior: no space before or after.

**Comment by didoesdigital** [comment]
Thanks for sharing.

The "exact spacing" setting is useful for certain kinds of lessons like fingerspelling, punctuation, numbers, code, and any lesson where you don't want any spaces between "words".

I think the behaviour is correct but maybe what it's for could be made clearer. Let's update the issue to clarify rather than change the behaviour.

There are some details on the about page about spacing. That might be a good place to document the 4 spacing settings and how you might use the "exact spacing" setting.

**Comment by na2hiro** [comment]
Thanks! That makes sense.

Since those lessons where the setting is useful has hint message to suggest it, I feel like it's not an issue.
