### ISSUE TITLE
[BUG] All lookup entries show `⌨️ Typey Type`

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/typey-type#207]
Hi. After #202 was cherry-picked, all entries show up like they're part of `typey-type.json` dictionary:
![Screenshot_2024-12-22-09-00-06-340_com.brave.browser.jpg](https://github.com/user-attachments/assets/9c6b75d0-f77a-42a4-bd6d-a8416a294ef9)

**Comment by didoesdigital** [comment]
Thanks for flagging the confusion @Monniasza 

As of this week, Typey Type now has a "[Full Dictionary](https://didoesdigital.com/typey-type/dictionaries/typey-type/typey-type-full/)" that I recommend students use instead of Plover's main.json for learning Plover theory. I wrote about it in more detail in a public Patreon post: https://www.patreon.com/posts/typey-type-now-118256473

I'll also include the salient details here…

Firstly, the "standard set" of dictionaries from the [steno-dictionaries repo](https://github.com/didoesdigital/steno-dictionaries/) that power Typey Type are now available as a single ["Full dictionary"](https://didoesdigital.com/typey-type/dictionaries/typey-type/typey-type-full/) download. From now on, I will be recommending that students using Typey Type with Plover theory use that dictionary instead of Plover's main dictionary.

The filename for that dictionary is `typey-type-full.json`. Previously, there was an unsorted, generated dictionary called `typey-type.json` that was used to collect the preferred stroke hint entries. It contained only 1 entry per word (sometimes referred to as "brief solitude") and I shall henceforth refer to that as the "slim dictionary". Some folk tried to used that instead of Plover's dictionary but didn't know it was not a full substitute. The "Full dictionary" aims to rectify that.

In the Lookup and stroke hints across the site, Typey Type now only uses the dictionaries that make up the Full Dictionary and no longer shows Plover dictionary entries. Previously, Typey Type showed 1 hint of its own plus others from Plover's dictionary.

Typey Type now shows outlines from that standard set of dictionaries all over the place: lesson hints, creating a custom lesson from a word list, the Lookup page, game hints, and the stroke lookup on the dictionaries index page and flashcards pages. I've removed Plover's dictionary from all of those places.

The [steno-dictionaries repo](https://github.com/didoesdigital/steno-dictionaries/) includes a `top-10000-project-gutenberg-words.json` dictionary. This has become a way for us to capture the preferred stroke for the most common words from Project Gutenberg (which is a nice big source of English sentences). These are the words students are most likely to use, so it was a good place to start for improving stroke hints.

While there's now a "Full dictionary" available, Typey Type technically uses the standard set of dictionaries that make up the full dictionary for stroke hints. This is because that standard set includes the `top-10000-project-gutenberg-words.json` dictionary so that Typey Type will suggest its entries as hints over other entries available in the full dictionary.
