### ISSUE TITLE
Ignore leading spaces in search bar of lookup page

### ISSUE THREAD

**Issue by rabbitgrowth** [didoesdigital/typey-type#25]
When a user fingerspells a word in the search bar of the [lookup page](https://didoesdigital.com/typey-type/lookup), Plover might output a space at the beginning. For example, if the user types `A*` `TKPW*` `O*` to look up 'ago', Plover might output <code>&nbsp;AGO</code>:

<img width="615" alt="Screenshot 2020-05-06 at 9 59 22 PM" src="https://user-images.githubusercontent.com/64907596/81187099-2db04c00-8fe6-11ea-996c-e640115ebe6b.png">

Currently, this leads to the word failing to match, and the user would have to suppress the initial space with `TK-LS`. This could be a minor nuisance for some. Would it be possible to ignore leading spaces in search strings to make the lookup process smoother?

**Comment by didoesdigital** [comment]
You can now [look up " ago"](https://didoesdigital.com/typey-type/lookup?q=%20ago) and other words with spaces:

![image](https://user-images.githubusercontent.com/2476974/82205157-7999b400-9949-11ea-9974-8efdaa0d1710.png)

It continues to show different strokes for [opening](https://didoesdigital.com/typey-type/lookup?q=%20%22) or [closing quotes](https://didoesdigital.com/typey-type/lookup?q=%22%20):

![image](https://user-images.githubusercontent.com/2476974/82205264-a51c9e80-9949-11ea-998f-cfd3fe9b40bd.png)

![image](https://user-images.githubusercontent.com/2476974/82205326-c54c5d80-9949-11ea-9325-8f93ecf1a84d.png)


Fixed in 93a5d94
