### ISSUE TITLE
Medical Prefix/Suffix lessons require stroking of caret (^) character

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/typey-type#36]
In the [Medical prefixes](https://didoesdigital.com/typey-type/lessons/collections/medical/medical-prefixes/) and [Medical suffixes](https://didoesdigital.com/typey-type/lessons/collections/medical/medical-suffixes/) lessons, as opposed to the [Prefixes](https://didoesdigital.com/typey-type/lessons/drills/prefixes/) and [Suffixes](https://didoesdigital.com/typey-type/lessons/drills/suffixes/) lessons, explicitly stroking the caret (^) character is required in order to progress to the next word.

I'm going to wager that this was not intentional, but in the event that it was, would it be more preferred to have these two sets of lessons act in the same way?

**Comment by didoesdigital** [comment]
Good catch! It was not intentional, and it was a pretty straight forward fix in https://github.com/didoesdigital/typey-type/commit/6fba9a7483fd32d3bd592fc847f75895822fe049 to update the submodule with fix in https://github.com/didoesdigital/typey-type-data/commit/4ec2c5b11c2bcdc970318817fdf4f01f4ff52857. Thanks @paulfioravanti
