### ISSUE TITLE
"Give feedback on this lesson" link should be n/a in Custom Lesson

### ISSUE THREAD

**Issue by YannCebron** [didoesdigital/typey-type#86]
%subj%

**Comment by didoesdigital** [comment]
Thanks for filing this issue @YannCebron . When I click on the "Give feedback on this lesson" link in a custom lesson, I see a Google form showing the lesson path like this:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/2476974/181729986-44d6047a-e670-448c-b298-a1c63549569c.png">

That's useful information for me when people submit the form. Is that what you see? What do you expect to see?

**Comment by YannCebron** [comment]
I'm not sure what kind of feedback for custom (private content) lessons would be valuable for you to receive? Other than "general" bug reports, but they could be very specific to the lesson contents.

**Comment by didoesdigital** [comment]
It's helpful for debugging when people ask questions about lesson behaviour that's actually a result of custom material they've used rather than typical Typey Type behaviour. I guess the end result is nearly the same if I see "n/a" or "/lessons/custom" as I'll know that's a result of feedback after doing a custom lesson.

Thanks for the suggestion. It's less effort to leave it as it is and I don't think there's any harm by leaving it so I'll mark this as closed. Feel free to re-open if there are other considerations.
